import Head from "next/head"
import App from "./_app"



export default function Home() {
  return (
    <div>
    <Head>
      <title>My Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    </Head>
      <main>
        <App></App>
      </main>
    </div>
  )
}
